### ISSUE TITLE
Teacher Updates tab not switching when not signed in

### ISSUE THREAD

**Issue by yugaan24x7** [Ceres445/Team-10-Python-Project#19]
**Describe the bug**

**To Reproduce**
1. Go to 'https://school-portal-ceres.herokuapp.com/'
2. Click on 'Teacher Updates'
3. Even after clicking the Teacher Updates it has a round white box around 

**Expected behavior**
The white box is expected tp disappear after clicking it

**Screenshots**
![image](https://user-images.githubusercontent.com/77913635/126306639-0882e7d8-d05f-4a74-b939-452f4870dbd9.png)
in the above image I have already clicked the teacher update but it still has a round box around it.
![Screenshot 2021-07-20 at 3 46 41 PM](https://user-images.githubusercontent.com/42400528/126307485-ad9002c3-8008-40ca-b56e-59d89786ee73.png)

**Comment by Ceres445** [comment]
The teacher updates tab isn't being activated when user is not signed in/ no posts in any class
