### ISSUE TITLE
Populate Homepage

### ISSUE THREAD

**Issue by Ceres445** [Ceres445/Team-10-Python-Project#8]
**#Functionality:**

- Public Forum

- [x] All users can post

- Website Updates

- [x] Admins can release updates

- School Update
- [x] Students and teachers can post

- [x] Restrict usage for anonymous users

- [x] Make cooldown

#**Implementation**:
   - To submit without reloading
              - use js to make post request to server and update when approved
   - use js to get cooldown data and run timer

**Comment by zyugyzarc** [comment]
you can check off the last one now
